apiVersion: apps/v1
kind: Deployment
metadata:
  name: f2ml-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: f2ml-deploy
  template:
    metadata:
      name: f2ml-deploy
      labels:
        app: f2ml-deploy
    spec:
      containers:
      - name: f2mlcontainer
        image: f2mlregistryintegration.azurecr.io/nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: f2ml-service
spec:
  type: LoadBalancer
  loadBalancerIP: 40.68.85.241
  ports:
  - port: 80
  selector:
    app: f2ml-deploy

